version: "3"

services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=test
